Doer-org/TomoShiru

client/.husky/pre-commit, client/package.json, client/pnpm-lock.yaml
=> chore(client): add husky

server/api/Program.fs, server/api/api.fsproj, server/api/api.sln, server/database/mysql/sql/1_init_table.sql, server/docker/docker-compose.local.server.yaml
=> chore(server): local dbとの疎通を確認

server/README.md
=> docs(server): add readme

client/src/ui/avator/components/avator.tsx, client/src/ui/avator/components/index.ts, client/src/ui/avator/index.ts, client/src/ui/avator/stories/avator.stories.tsx, client/src/ui/avator/styles/avator.css.ts
=> Feat(avator): アバターコンポーネント追加

server/fake.sh
```
% sh fake.sh re
run -n re
Target "-n re" is not defined. 
```
を直した
=> fix(server): fake file

client/src/ui/avator/stories/avator.stories.tsx, client/src/ui/button/stories/button.stories.tsx
=> Chore(stories): change story meta

client/src/ui/card/components/card.tsx, client/src/ui/card/components/index.ts, client/src/ui/card/index.ts, client/src/ui/card/stories/card.stories.tsx, client/src/ui/card/styles/card.css.ts
=> Feat(card): カードコンポーネント追加

client/src/app/profile/page.tsx
=> chore(client): remove console.log

client/src/middleware.ts
=> fix(client): cookie

client/.storybook/main.ts
=> Chore(client): storybookに設定を追加

client/src/ui/hamburger/components/hamburger.tsx, client/src/ui/hamburger/components/index.ts, client/src/ui/hamburger/index.ts, client/src/ui/hamburger/stories/hamburger.stories.tsx, client/src/ui/hamburger/styles/hamburger.css.ts
=> Feat(client): ハンバーガーメニューを作成

client/src/ui/arrow/components/arrow.tsx, client/src/ui/arrow/components/index.ts, client/src/ui/arrow/index.ts, client/src/ui/arrow/stories/arrow.stories.tsx, client/src/ui/arrow/styles/arrow.css.ts, client/src/ui/index.ts
=> Feat(client): 戻るボタンを追加

client/src/ui/search-result/stories/search-result.stories.tsx
=> storybookの修正

client/src/ui/index.ts, client/src/ui/ranking/components/index.ts, client/src/ui/ranking/components/ranking.tsx, client/src/ui/ranking/index.ts, client/src/ui/ranking/stories/ranking.stories.tsx, client/src/ui/ranking/styles/ranking.css.ts
=> ランキングコンポーネント作成

client/src/libs/graphql-client.ts
=> chore(client): token

client/src/api/spotify/artist/index.ts, client/src/api/spotify/client/client.ts, client/src/api/spotify/search/index.ts, client/src/app/(common)/search/page.tsx, client/src/utils/env.ts
=> Chore(client): SpotifyAPI雑事

client/src/app/_ui/index.ts, client/src/app/debug/_ui/debug-button/components/debug-button.tsx, client/src/app/debug/_ui/debug-button/components/index.ts, client/src/app/debug/_ui/debug-button/index.ts, client/src/app/debug/_ui/debug-graphql-button/components/debug-button.tsx, client/src/app/debug/_ui/debug-graphql-button/components/index.ts, client/src/app/debug/_ui/debug-graphql-button/index.ts, client/src/app/debug/_ui/index.ts, client/src/app/debug/layout.tsx, client/src/app/debug/page.tsx, client/src/app/debug/profile/layout.tsx, client/src/app/debug/profile/page.tsx, client/src/app/profile/page.tsx
=> feat(client): debugページを切り出す

client/src/utils/graphql/generated/graphql.tsx, server/api/Domain.fs, server/api/GraphQL/Handler.fs, server/api/GraphQL/Schema/Mutation.fs, server/api/GraphQL/Schema/Query.fs, server/api/GraphQL/Util.fs
=> refactor(api): jwt validator

client/src/middleware.ts
=> chore(client): auth middleware

client/src/app/_ui/profile-header/styles/profile-header.css.ts
=> chore(client); ヘッダーのスタイル修正

client/src/app/(authed)/timeline/[id]/page.tsx, client/src/app/(authed)/timeline/page.tsx, client/src/app/_ui/notice-card/components/notice-card.tsx, client/src/app/_ui/notice-card/stories/notice-card.stories.tsx
=> Feat(client): timeline/:id ページを作成

client/src/app/(authed)/profile/[id]/page.tsx, client/src/app/(authed)/profile/page.tsx, client/src/app/(authed)/timeline/page.tsx, client/src/app/(not-authed)/debug/page.tsx, client/src/app/page.tsx
=> fix(client): 各page.tsxにuse clientを付与

client/src/app/_ui/nav-menu/styles/nav-menu.css.ts
=> chore(client);navi-menuのスタイル修正

client/src/app/(authed)/notification/[id]/layout.tsx, client/src/app/(authed)/notification/[id]/page.tsx, client/src/app/(authed)/notification/_styles/notification.css.ts
=> feat(client): 通知ページを追加

client/src/app/(authed)/bookmark/[id]/page.tsx, client/src/app/(authed)/bookmark/_styles/bookmark.css.ts
=> feat(client): いいね一覧ページの追加

client/src/app/(authed)/_styles/common.css.ts, client/src/app/(authed)/bookmark/[id]/page.tsx, client/src/app/(authed)/bookmark/_styles/bookmark.css.ts, client/src/app/(authed)/notification/[id]/layout.tsx, client/src/app/(authed)/profile/[id]/edit/page.tsx, client/src/app/(authed)/profile/[id]/page.tsx, client/src/app/(authed)/profile/_styles/profile.css.ts, client/src/app/(authed)/profile/follow/[id]/page.tsx, client/src/app/(authed)/profile/follow/_styles/follow.css.ts, client/src/app/(authed)/profile/follower/[id]/page.tsx, client/src/app/(authed)/profile/follower/_styles/follower.css.ts, client/src/app/(authed)/search/layout.tsx, client/src/app/(authed)/timeline/layout.tsx, client/src/app/_ui/common-header/styles/common-header.css.ts
=> refactor(client): styleの読み込み方法を修正

client/src/middleware.ts, server/.gitignore
=> chore: update gitignore

client/src/middleware.ts
=> chore(client): update middleware

client/src/middleware.ts
=> chore: test

client/src/middleware.ts
=> refactor(client): middleware

client/src/middleware.ts
=> chore(client): middleware

client/src/app/(authed)/bookmark/[id]/page.tsx, client/src/app/(authed)/bookmark/_styles/bookmark.css.ts, client/src/app/(authed)/notification/[id]/page.tsx, client/src/app/(authed)/profile/follow/[id]/page.tsx, client/src/app/(authed)/profile/follow/_styles/follow.css.ts, client/src/app/(authed)/profile/follower/[id]/page.tsx, client/src/app/(authed)/profile/follower/_styles/follower.css.ts, client/src/app/(authed)/timeline/[id]/page.tsx, client/src/app/(authed)/timeline/_styles/timeline.css.ts, client/src/app/_ui/notice-card/components/notice-card.tsx
=> Refactor(client): クライアント繋ぎこみ

client/src/app/(authed)/bookmark/[id]/page.tsx, client/src/app/(authed)/profile/follow/[id]/page.tsx, client/src/app/(authed)/profile/follower/[id]/page.tsx, client/src/app/(authed)/timeline/[id]/page.tsx, client/src/app/_ui/nav-footer/components/nav-footer.tsx, client/src/app/_ui/nav-footer/stories/nav-footer.stories.tsx, client/src/app/_ui/notice-card/components/notice-card.tsx, client/src/app/_ui/notice-card/stories/notice-card.stories.tsx, client/src/app/_ui/profile-header/components/profile-header.tsx, client/src/app/layout.tsx, client/src/ui/avator/components/avator.tsx
=> image_urlを適用

client/src/app/(authed)/layout.tsx, client/src/app/_ui/nav-footer/components/nav-footer.tsx, client/src/app/_ui/nav-menu/components/nav-menu.tsx
=> Authinfoを取得してデータ表示

client/src/app/(authed)/_styles/common.css.ts
=> fix: ヘッダー回避修正

client/src/app/page.tsx, client/src/ui/logo/components/logo.tsx, client/src/ui/logo/stories/logo.stories.tsx, client/src/ui/logo/styles/logo.css.ts
=> logoコンポーネント調整

client/src/app/(authed)/bookmark/[id]/page.tsx, client/src/app/(authed)/profile/[id]/edit/page.tsx, client/src/app/(authed)/profile/[id]/page.tsx, client/src/ui/avator/components/avator.tsx, client/src/ui/avator/styles/avator.css.ts, client/src/ui/like/components/like.tsx, client/src/ui/like/stories/like.stories.tsx
=> feat(client): いいね機能

.vscode/settings.json, server/.config/dotnet-tools.json, server/.editorconfig, server/api/Auth.fs, server/api/Database/FavoriteArtist.fs, server/api/Database/FavoriteMusic.fs, server/api/Database/FavoriteRamenya.fs, server/api/Database/Follow.fs, server/api/Database/Log.fs, server/api/Database/ProfileChangeLog.fs, server/api/Database/Reaction.fs, server/api/Domain.fs, server/api/GraphQL/Handler.fs, server/api/GraphQL/Schema/Mutation.fs, server/api/GraphQL/Schema/Query.fs, server/api/GraphQL/Schema/Types.fs, server/api/GraphQL/Util.fs, server/api/Program.fs, server/api/Rest/Handlers.fs, server/api/Store.fs, server/api/Utils.fs
=> feat(server): fantomas

.github/workflows/build-check-server.yaml
=> ci(server): build check
